### ISSUE TITLE
how long does it take to refresh the frontend normally? 

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#10]
seems like we wait hours - is this normal?

**Comment by evansavage** [comment]
The order variables are still getting messed up every time content is saved on the CMS. I need to make sure every single page is templated through Forestry, which I am going to do manually now.

**Comment by macdonaldc** [comment]
ah ok thanks

**Comment by evansavage** [comment]
Every page is templated on the Forestry side of things, so content updates shouldn't cause issues now.
