### ISSUE TITLE
title for example accordion

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#11]
is it possible to set a variable for the accordion title?
so the default could be example but we can override it?

**Comment by evansavage** [comment]
Yes that is definitely possible. If there is a title, do you want it to show up like:

Example 1: < title >

or just

< title >

Also, in the latter case above, say there is first an example with a title, then one without, should the second one be listed as Example 2? Or remove the numbering?

**Comment by macdonaldc** [comment]
just <title> 
let's keep the auto numbering

**Comment by evansavage** [comment]
Like I said in the meeting, you can just add the title variable to include specific text.
