### ISSUE TITLE
There are two 4.1 sections now

### ISSUE THREAD

**Issue by evansavage** [mat3rial/ARCA#12]
Which one is correct and do they need to be renamed?

* en/_posts/2020-05-27-4-1-exchange-of-services-of-equal-value.md
* en/_posts/2020-05-27-4-1-evaluation-of-the-donation.md

**Comment by macdonaldc** [comment]
the second one will become 2-1
there's a lot of reorg to do now because the structure changed.
i put all the correct numbering in the titles

**Comment by macdonaldc** [comment]
all posts have now been added

**Comment by evansavage** [comment]
Ok i think this one can be closed.
