### ISSUE TITLE
how to link to files

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#14]
Can you tell me how to add the links for files, eg: https://mat3rial.github.io/ARCA/en/toolkit/procedures/

**Comment by evansavage** [comment]
Yep! It is a file path convention that just will just depend on the location of the file like you anticipated. Just missing one thing! It will be formatted just like a link to any external URL:

\[Text for link\](*url*)

Except now, it needs to reference the relative folder destination after the domain URL with {{ site.baseurl }}, which is a variable you'll need to use each time. So for the example at that link above, it will be:

[Donation Procedure]({{ site.baseurl }}/assets/procedures/donation_procedure.doc)
