### ISSUE TITLE
Guide navigation footer

### ISSUE THREAD

**Issue by evansavage** [mat3rial/ARCA#16]
How deep do you want the navigation to go? The visual mockup only shows a depth of 2, i.e.:

- 1 Intro
- 2 Section
  - 2.1 Subsection

But section 2 has a depth of 3 in the guide. Should it be dynamic and change the depths between sections?

**Comment by macdonaldc** [comment]
I'll discuss this with Antonia today, since their changes have thrown off our expectations about the footer layout.

**Comment by macdonaldc** [comment]
but my gut feeling is to keep to 2 levels

**Comment by evansavage** [comment]
Should the sections in the footer just be text and not links? Or should people be able to click on them to go to the relevant sections?

**Comment by macdonaldc** [comment]
links would be great

**Comment by evansavage** [comment]
Just re-open this if the depth needs to go any further down!
