### ISSUE TITLE
New forestry content not appearing on site

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#2]
I have updated the content for the 1-Introduction page on the French side, but my revisions do not appear on the site.

Here is my content: https://app.forestry.io/sites/huwc--mld356-q/#/pages/fr-_posts-2020-05-27-1-introduction-md/

Here is the page: https://mat3rial.github.io/ARCA/fr/guide/1-introduction/

**Comment by evansavage** [comment]
I see the site is having some build error troubles! I will look into it by the end of the weekend.

**Comment by evansavage** [comment]
It had to do with the order variable in the page being saved as a string instead of the number, and it couldn't be used for comparisons I am making in the background as such. It shouldn't happen again!

**Comment by macdonaldc** [comment]
hey thanks evan :) btw you don't need to work on the weekend even if I am!
