### ISSUE TITLE
forestry edits not updating on site

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#25]
I'm making some edits today and it seems like my changes have just stopped being updated in the site

**Comment by evansavage** [comment]
I will look into this soon!

**Comment by evansavage** [comment]
I see there is a new syntax in some spots, the {: .toolkit} references. What are those for? They are unrecognized by Jekyll and that is what is causing the page build errors.

**Comment by macdonaldc** [comment]
I thought I found a way to apply classes to markdown, guess not?

**Comment by macdonaldc** [comment]
it does actually add the class to the html, there are some in there that work I think I will try to find it

**Comment by macdonaldc** [comment]
no those were using <a> tags ok i will convert them all

**Comment by evansavage** [comment]
This is only a problem for Jekyll when it is in the accordion example! It seems to be ok everywhere else. So do we need a specific field for adding links? Might be just better to manually code that accordion example

**Comment by evansavage** [comment]
The problem is the whole link within the example_text variable, not just the {: .toolkit} text

**Comment by macdonaldc** [comment]
So this a sample of what I've been using... is this whole format wrong or just the last part?

[See Diagram 1]({{ site.baseurl }}/en/toolkit/diagrams/){: .toolkit}

**Comment by evansavage** [comment]
All of that is fine! It only can't be done inside the accordion_example snippet. So, on /fr/guide/2_1_2-dons-de-services/, there is an example accordion with a link like that inside the example_text variable, and Jekyll can't parse it correctly. I can just change the accordion there to explicit HTML code and that will work if that's preferred!

**Comment by evansavage** [comment]
I just went ahead with it, everything is working now!
