### ISSUE TITLE
is it easy to add text variable for 'next step' button?

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#33]
in some cases they want to replace 'next step' with other text - is this easy enough to set up?

**Comment by evansavage** [comment]
Yes, will reconfigure the corresponding elements

**Comment by evansavage** [comment]
The nav_yes_no and next_step_button includes now have an optional _nextText_ variable for specifying the text if needed. Open this issue back up if it's not functioning how you'd expect
