### ISSUE TITLE
border misalignment

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#36]
maybe this is a clue...

on this page the borders are aligned for me in Chrome and FF: https://mat3rial.github.io/ARCA/en/guide/end/

on all the other pages they are not

**Comment by macdonaldc** [comment]
also now that I removed text from this page it aligns:
https://mat3rial.github.io/ARCA/fr/guide/1-consid%C3%A9rations/

**Comment by evansavage** [comment]
I still cannot replicate any of these errors in Firefox, Chrome, or Safari :(

**Comment by macdonaldc** [comment]
the client also sees this so we're going to have to figure it out - maybe we know a css wizard who can figure it out?

**Comment by evansavage** [comment]
This is fixed now for you across all pages yes?

**Comment by macdonaldc** [comment]
yes it's fixed :)
