### ISSUE TITLE
anchor links in page overshoot their mark

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#37]
I added anchor links in markdown in the about page
https://mat3rial.github.io/ARCA/en/about#challenges

the problem is that the link overshoots the header that I'm trying to link to...
I've seen this before I think it's because of the fixed header. Maybe needs some kind of js to resolve?

**Comment by macdonaldc** [comment]
i just commented out the anchor links for now but they are still there

**Comment by evansavage** [comment]
I just pushed a possible solution using negative margins and padding after some experimentation. There is a new CSS property being integrated for this (scroll-padding-top on the html element), but it's not functional on Safari yet!!

**Comment by evansavage** [comment]
Are all the anchor links to h2 elements? Any other elements? I will need to include those in the CSS if so

**Comment by macdonaldc** [comment]
only for the h2 tags in that page, although I guess the corresponding paragraph text will also need to be pushed down

**Comment by evansavage** [comment]
The paragraphs are still aligned with everything fine, thinks seem to be working ok on my end with this one, will close!
