### ISSUE TITLE
footer issue in some browsers

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#41]
two people reported this problem - one using Safari and one using Brave

even on a short page like this one: https://mat3rial.github.io/ARCA/en/guide/1-start/

apparently the footer is way below and they have to scroll way down to find it

**Comment by evansavage** [comment]
I am not able to replicate on Safari. This is really odd! I have not come across cross-device same-browser problems before. I will download Brave and check there.

**Comment by macdonaldc** [comment]
it's ok we can leave this - one of the feedbacks was about moving the navigation completely - to the left instead of bottom. 
So this won't be an issue any more.
