### ISSUE TITLE
new left menu headers

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#47]
to shorten it up a bit we'll use these shorter versions in the menu if this works...

1. Départ
2. Comptabilisation des dons
3. Comptabilisation des échanges
4. Incidence de l'application de la taxe
5. Organisme de bienfaisance: reçus

1. Start
2. Accounting for Contributions
3. Accounting for Exchanges
4. Impact of Applying Taxes
5. Charitable Organizations: Receipts

**Comment by macdonaldc** [comment]
oops github reordered my lists... first 1-5 in list are the French headers, 6-10 is the English headers

**Comment by evansavage** [comment]
Do you mean the new sidebar menu or in the top navigation or both?

**Comment by evansavage** [comment]
And should each of these titles in the new side navigation act as a dropdown regardless of what page you are on? Or should the subsections only show for the relevant section that the user is currently in?

**Comment by evansavage** [comment]
In the latter case, that would force the user to navigate to the starting page for each section if they wanted to jump around. For example, they wouldn't be able to access 3.2 (only 3) from 2.2.

**Comment by evansavage** [comment]
One more question: as you scroll down the page, do you want the side nav to stay fixed or scroll with the content?

**Comment by macdonaldc** [comment]
> 
> 
> Do you mean the new sidebar menu or in the top navigation or both? **- this is in the sidebar nav**
> 
> And should each of these titles in the new side navigation act as a dropdown regardless of what page you are on? **- YES**

> One more question: as you scroll down the page, do you want the side nav to stay fixed or scroll with the content? **- I didn't think of this but it might be cool if it scrolls if that's easy to do**

**Comment by evansavage** [comment]
I will upload the initial sidebar changes, and you let me know if you like the side column moving how it is now, or if you would prefer it to stay stationary as you scroll. I wanna make sure we're on the same page! Dropdowns will be added later.

**Comment by macdonaldc** [comment]
ok, let's make it fixed I think that works better.

Also, let's change the fonts in the new nav to be the same size and weight as the top menu

**Comment by evansavage** [comment]
Font weights and sizes have been updated! The text on the sidenav looks a little smaller than the top in some sort of illusion, but it is the same!

**Comment by macdonaldc** [comment]
looks good, but now i'm seeing really weird scrollbars all over the site in chrome and FF
i'll have to send you a screen capture by email

**Comment by macdonaldc** [comment]
in French, the last menu item is missing the 5. at the beginning

**Comment by macdonaldc** [comment]
In English 3. Accounting for exchanges 
should be Exchanges (capitalized)

**Comment by evansavage** [comment]
These changes should now be reflected.

**Comment by evansavage** [comment]
Will close for now, reopen if I forgot something!
