### ISSUE TITLE
change formatting of left menu + fix

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#48]
can we make all the menu items on the left the same size, ie. no <h3>?

also can you fix the menu on the side when we scroll?

**Comment by macdonaldc** [comment]
oops i wrote no h3 tag

**Comment by evansavage** [comment]
Yes can do! Sorry thesis stuff has been keeping me very busy! I will implement a fix by the end of the day today.

**Comment by macdonaldc** [comment]
np
also in the French menu the capitalization should be just first letter cap all the rest lower case

**Comment by evansavage** [comment]
My apologies I have not gotten to this yet! Thesis stuff is soon wrapping up. Will finally get to it tomorrow.

**Comment by macdonaldc** [comment]
no worries!
i adjusted the font already

**Comment by evansavage** [comment]
Woops! I may have then overrode your recent changes! The nav is now fixed, and scrolls individually of the content on the right side if the expanded dropdowns make it too tall.
