### ISSUE TITLE
launch info

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#54]
I hope this is feasible - the site needs to appear in two different places

arca.art/fr/pasjusteunequestiondargent
- at this address we will display the following page: https://mat3rial.github.io/ARCA/fr/

arca.art/en/notjustaboutthemoney
- at this address we will display: https://mat3rial.github.io/ARCA/en/

obviously users will be able to flip languages in both locations, but they need different entry points on the ARCA site

let me know if this will work or we need to propose something else

**Comment by evansavage** [comment]
I think we can make it work, do you have access to the domain name service for the existing ARCA website?

**Comment by macdonaldc** [comment]
the login has changed, I'll have to ask for the new info

**Comment by macdonaldc** [comment]
i got into their control panel, what exactly would i need to do in here?

**Comment by evansavage** [comment]
We will need the DNS to point here, and here to point to the DNS. Do you want the language-specific subdomain to always show when you are going through other pages in the guide? For example, on the English 'glossary' page would you like to see: arca.art/en/notjustaboutthemoney/toolkit/glossary/?

**Comment by macdonaldc** [comment]
there is weird language issue because we have the language of the ARCA site and then the language of the guide within it

I think we have to make en and fr available from both language entry points in the ARCA site - i don't see another way unless we remove the language switcher from our menu which i don't think is a good idea

in your example above without the second 'en' what would happen if users click on the 'fr' in the menu?
would they be redirected to the french home page of the guide arca/art/fr/pasjusteunequestiondargent ?

I don't think this would work because users need to be able to switch back and forth within a specific page.

so as weird as it seems I think we will need to set it up so the following options are possible:
arca.art/en/notjustaboutthemoney/en/toolkit/glossary
arca.art/en/notjustaboutthemoney/fr/boîte_à_outils/lexique/
arca.art/fr/pasjusteunequestiondargent/fr/boîte_à_outils/lexique/
arca.art/fr/pasjusteunequestiondargent/en/toolkit/glossary

unless there is another solution for this problem?

**Comment by evansavage** [comment]
This will be a bit tricky to figure out, since everything up until the .../en/ and .../fr/ in the current URL can be replaced by one domain name, and nothing more.

**Comment by evansavage** [comment]
So is there some way to get to a language independent option on the arca.art domain? I think that would yield the best option

**Comment by macdonaldc** [comment]
the only problem for them as finding a language neutral url
this one for example is way too unwieldy:
arca.art/notjustaboutthemoney-pasjusteunequestiondargent

**Comment by macdonaldc** [comment]
i guess we could use the pages 
arca.art/en/notjustaboutthemoney
arca.art/fr/pasjusteunequestiondargent

to redirect to a language neutral url
but they can use those shorter links above to share the resource online maybe?

**Comment by macdonaldc** [comment]
i have to ask her about this

**Comment by evansavage** [comment]
That's a good idea, because then we could specifically link to the language relevant version more easily.

arca.art/en/notjustaboutthemoney -> \<language-neutral-url\>/en/
arca.art/fr/pasjusteunequestiondargent -> \<language-neutral-url\>/fr/ 

Both of which can be easily, explicitly specified.

**Comment by macdonaldc** [comment]
yeah would be better, i wrote to them about it

**Comment by macdonaldc** [comment]
Ok they agree to our solution.

DNS: 
ns1.fuseddns.com 
ns2.fuseddns.com

**Comment by evansavage** [comment]
What are those URLs?

**Comment by macdonaldc** [comment]
those are the domain name servers...
what do you need instead?

**Comment by evansavage** [comment]
We need a single language-neutral URL that the current site can be linked to. Is either one of those the choice?

**Comment by macdonaldc** [comment]
it will be this:
arca.art/notjustaboutthemoney-pasjusteunequestiondargent

**Comment by evansavage** [comment]
Ok so when we want it to go live, we specify that URL (**arca.art/notjustaboutthemoney-pasjusteunequestiondargent**) here in the repo on the '**Settings**' tab at the top, inside the '**Custom domain**' field. Then, on the DNS side, we need to add a CNAME record that points '**arca.art/notjustaboutthemoney-pasjusteunequestiondargent**' to '**mat3rial.github.io/ARCA/**'.

Full instructions can be found here: https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by macdonaldc** [comment]
getting an error message that the format of the custom domain is not valid...
looking at this page - does it mean we set the domain to arca.art and the project will appear at arca.art/ARCA ?
https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages#supported-custom-domains

**Comment by evansavage** [comment]
Oh yes, we will need to use that as the custom domain then, but I can change the /ARCA part of the URL to the 'notjustaboutthemoney-pasjusteunequestiondargent' text, and it should hopefully work!

**Comment by macdonaldc** [comment]
ok do this definitely won't overwrite the site as arca.art right?

**Comment by evansavage** [comment]
Will not overwrite, may show this website instead if we're off our mark, but it will be able to be rerouted back to the original website in the worst case. I changed the baseurl and repo name to 'notjustaboutthemoney-pasjusteunequestiondargent'

**Comment by macdonaldc** [comment]
ok i changed the settings to custom domain = arca.art

but when i try to add a new cname it won't let me add a url with a subfolder, eg. 
arca.art/notjustaboutthemoney-pasjusteunequestiondargent

is not valid

**Comment by evansavage** [comment]
From this paragraph at https://docs.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages:

*After you configure a custom domain for a user or organization site, the custom domain will replace the \<user\>.github.io or \<organization\>.github.io portion of the URL for any project sites owned by the account that do not have a custom domain configured. For example, if the custom domain for your user site is www.octocat.com, and you have a project site with no custom domain configured that is published from a repository called octo-project, the GitHub Pages site for that repository will be available at www.octocat.com/octo-project.*

It sounds like the DNS side can point to just 'mat3rial.github.io' and it should work out

**Comment by evansavage** [comment]
It seems that we may actually need a subdomain in the form *notjustaboutthemoney-pasjusteunequestiondargent.arca.art* to make it work.

Then, the GitHub side points to: *notjustaboutthemoney-pasjusteunequestiondargent.arca.art* 

CNAME on DNS is configured as:
- subdomain: *notjustaboutthemoney-pasjusteunequestiondargent*
- TTL: *By default* (If this is an option)
- target: *mat3rial.github.io.* (**note the period at the end**)

This is from: https://stackoverflow.com/questions/46455900/subdomain-of-website-for-github-pages-project

**Comment by macdonaldc** [comment]
ok i created the subdomain on their server...
but it won't let me create a CNAME because it says there is already an A record...
"pasjusteunequestiondargent.arca.art. already has a A record. You may not mix CNAME records with other records for the same name."
So do I delete the A records and add CNAME instead?

**Comment by macdonaldc** [comment]
I can't delete them so I'll have to write to their hosting support...

**Comment by macdonaldc** [comment]
This is what the hosting guy said:
"CNAMEs do not have the ability to handle redirects — that bit is going to need to be on the github side.
If it can't be done there, we can configure a subdomain + redirect, but the final domain that shows in the browser will be the repo url."

**Comment by macdonaldc** [comment]
but you have done this before with other jeckyll sites right?
should I add you to the thread with this guy>

**Comment by evansavage** [comment]
Yes I have! And on subdomains! I have followed the GitHub Pages we are referencing here before, but not commonly with a subdomain connection, there is usually a "fresh" domain for connecting. And please do add me if you think that will help!

**Comment by macdonaldc** [comment]
just waiting a moment now because i think Anne wants to change the name of the subdomain...

**Comment by macdonaldc** [comment]
there's no way to have 2 subdomains is there?
pasjusteunequestiondargent.arca.art
notjustaboutthemoney.arca.art

**Comment by evansavage** [comment]
There probably is, but that would make things much more dicey for switching the same codebase between two different domains. Also, the github side can only point to one.

**Comment by evansavage** [comment]
We're close now! The first language page is showing up at the subdomain, just not the formatting!

**Comment by evansavage** [comment]
It's working!!

**Comment by macdonaldc** [comment]
weird...
well anne is potentially changing the name of the subdomain, so I'll have to set it up again later... but glad this is working, maybe it just takes time for the cname to propagate or something

**Comment by macdonaldc** [comment]
so what it looks like is the subdomain that i created on their hosting is gone, 
but there is now a cname directing that subdomain address to the github url
so i guess on the hosting end we don't really need to do anything it just creates a cname based on the custom domain settings in github
(?)

**Comment by evansavage** [comment]
Sorry for the delay! I would be surprised if the hosting end automatically created a CNAME record based on the GitHub configuration, so I am not totally sure! Are we sticking with the current subdomain then, or were you trying to change it?

**Comment by macdonaldc** [comment]
hmmm maybe they went ahead and did it for me... but they didn't mention it
still waiting for them to confirm if the subdomain name is going to change
