### ISSUE TITLE
about page messed up

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#55]
I replaced one letter and something weird happened cause now it looks like this...

https://mat3rial.github.io/ARCA/en/about

**Comment by evansavage** [comment]
This happened because of the guide page formatting changes. I will fix this tomorrow.

**Comment by evansavage** [comment]
This is hopefully now updated on your side. Let me know if the link boxes at the top should be positioned any differently.

**Comment by macdonaldc** [comment]
they're back in the right place but supposed to be formatted as links, not in a table

**Comment by evansavage** [comment]
Is it ok for them to be formatted as links inside the table? This was just easiest for formatting based on Antonia's designs.

**Comment by macdonaldc** [comment]
I would prefer them to show as they did originally:
Objective | Context | Challenges | Considerations
and each one was bold and underlined as a link

I don't know how this turned into a table - I made an edit somewhere else in the page and it happened.
They might ask us to make more changes later to this page and I'm worried it will happen again.
How can I prevent this?

**Comment by evansavage** [comment]
Markdown automatically formats tables with the ' | ' character which can be escaped by instead typing ' \\\| ' which avoids creating a table. I included this change and the page probably won't get messed up upon changes anymore as long as this syntax is maintained!

**Comment by macdonaldc** [comment]
ah ha mystery solved, thank u!
