### ISSUE TITLE
scroll bars appear on FF and Chrome on PC

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#56]
the client saw these as well so it's not just my computer that is looking weird

**Comment by evansavage** [comment]
I just implemented some code to hopefully remove them. Do we need to visually indicate to the users if there is a need to continue scrolling on desktop when the content is overflowing the outer frame, or should we believe that continued scrolling is intuitive?

**Comment by macdonaldc** [comment]
i just see the regular browser scrollbars now (not the scrollbars in the app itself) which i think will indicate that they should keep scrolling.
i am seeing one on the bottom of the browser though which is kind of weird - i guess it thinks there is some overflow horizontally?

**Comment by macdonaldc** [comment]
made a little video - the bottom scrollbar moves the borders ... 
https://drive.google.com/file/d/1Dc6ATn5jsZSI2b7mgnmJ3FxrIvx8p76O/view

**Comment by evansavage** [comment]
OK I'm at home now, where I finally have access to a Windows laptop. I will be diagnosing this later today.

**Comment by evansavage** [comment]
Might have figured out the issue, though I haven't been able to diagnose on Windows yet. The scrollbars on Windows browsers take up some of the page width, which would explain the slight offset from the header above. Changed the CSS to account for this (I believe), let me know if that fixed it, will not be able to access the laptop until later.

**Comment by evansavage** [comment]
I just was able to fix the body offsets on the Windows laptop, let me know if this change is finally reflected for you!

**Comment by macdonaldc** [comment]
yes!!! yay!! thank you

**Comment by evansavage** [comment]
I will close for now, it seems the issues here have been addressed!
