### ISSUE TITLE
home page overlapping

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#57]
so the site is officially launched now...
but I just noticed this issue in Chrome - I can't attach a screen capture here but it looks like the entire page is forced to fit within the browser window, and the footer is overlapping the red text that says "This guide is for you"
This happens at 100% zoom, when I go to 90% zoom in chrome it fits ok

If you have any time to help Evan can you let me know where I should look to fix this - the other pages don't seem to have the problem because the page scrolls past the bottom of the browser window
except here: http://silver-guide-argent.arca.art/en/

**Comment by evansavage** [comment]
I added a minimum height value to the home screen. Hopefully that works!

**Comment by macdonaldc** [comment]
it's great, thank you Evan!
