### ISSUE TITLE
change permalinks to reflect titles of posts

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#8]
do the en/fr permalinks have to be the same to enable the language switching?
if so I might have to rename all of them in a language-neutral way, when we're done adding the content

**Comment by macdonaldc** [comment]
some permalinks also will need to be changed, eg. numbering is wrong based on the final content

**Comment by evansavage** [comment]
The permalinks do not need to be the same. Only the langref variable between the two pages needs to be the same. Can you rename all the title variables in the french _posts folder? Then I can update the permalinks from there.

**Comment by evansavage** [comment]
That is the langref between the french and english version of the same document.

**Comment by macdonaldc** [comment]
ok great once i'm done adding all the content then I could do it if you want

**Comment by evansavage** [comment]
The permalinks should at least include the section number, I saw that you were using that syntax. Existing permalinks can be reduced to that as well! Just make sure there is always a trailing slash!  (e.g. /en/4-1-something/)

**Comment by evansavage** [comment]
I am changing the convention of the permalinks to help with the footer nav formatting on the guide. Please maintain this syntax if you need to change any:

- "/en/guide/\<num\>-<section_title>"
- "/en/guide/\<num\>_\<num\>-<section_title>"
- "/en/guide/\<num\>\_\<num\>\_\<num\>-<section_title>"

Between numbers, always use underscores, and use a hyphen to transition to the title.

**Comment by macdonaldc** [comment]
and underscores in the link tex too?
eg.
2-rules_to_follow

**Comment by evansavage** [comment]
Nope, keep hyphens between the words! I updated all the permalinks to highlight this.
