### ISSUE TITLE
Can I add new posts

### ISSUE THREAD

**Issue by macdonaldc** [mat3rial/ARCA#9]
As I'm going through the final content they gave us it is organized a bit differently from the original content. For example, I now need a section 2.1.1
Can I add new posts?

**Comment by macdonaldc** [comment]
Ok I see I can add them but then we'll have to figure out the order and langref after

**Comment by evansavage** [comment]
Go ahead and decide upon the langref yourself if you would like! For the two relevant documents, it will just have to be unique from all the other langrefs, that's the only condition.

**Comment by macdonaldc** [comment]
for the posts could we use the numbering as a langref? eg. 4-1 
or does it have to be alpha?

**Comment by evansavage** [comment]
Yeah the langrefs can be the section numbers I think, I will experiment with that now.

**Comment by evansavage** [comment]
All page langrefs have been changed to section numbers, great idea!!
